### ISSUE TITLE
Coordinate Tool - Add Degree Decimal Minute Option

### ISSUE THREAD

**Issue by topowright** [Esri/military-tools-webappbuilder#11]
_From @TonyGT on February 15, 2016 21:48_

Would be great to have Degree Decimal Minute as an option for coordinate display as this is used my many police agencies, especially on the water.

_Copied from original issue: Esri/solutions-webappbuilder-widgets#436_

**Comment by MarkTorrey** [comment]
Closed prior to being moved to this repo
