### ISSUE TITLE
CoordinateTool widget UTM doesn't use N or S for hemisphere.

### ISSUE THREAD

**Issue by topowright** [Esri/military-tools-webappbuilder#13]
_From @jmccausland on January 11, 2016 12:43_

The other tools were designed to use N or S for the hemisphere segment of the UTM coordinate.  If this is still valid we should keep them all the same.

_Copied from original issue: Esri/solutions-webappbuilder-widgets#401_

**Comment by MarkTorrey** [comment]
These were closed before being moved to this repo
