### ISSUE TITLE
Coordinate Tool manifest.json needs updating

### ISSUE THREAD

**Issue by topowright** [Esri/military-tools-webappbuilder#15]
_From @adgiles on January 27, 2016 12:56_

The name attribute in the manifest.json needs to be the same as the widget folder "CoordinateTool" otherwise the widget will not load in the builder

_Copied from original issue: Esri/solutions-webappbuilder-widgets#418_

**Comment by MarkTorrey** [comment]
Manifest files for both DistanceAndDirection and CoordinateConversion match the name of the widgets directory
