### ISSUE TITLE
Can not deploy Widgets to Web App Builder from Repository

### ISSUE THREAD

**Issue by conklinbd** [Esri/military-tools-webappbuilder#2]
When I copy the widget directly from the repository to stemapp/widgets the widget shows in the list but is missing the icon and can not be added. 

It seems like it is looking for files in folders based on the previous names for the tool. (CoordinateTool) instead of using the new folder names. 

I tried this on web-appbuilder-2.0 from Master branch. 

Changing the name of the folder fixes the icon loading and brings up an initial page for the tool but then the tool setting fail to load. Missing another file (settings.js). So generally the manifest and file locations seems incorrect. 

I am using the widget from the master branch.

**Comment by kgonzago** [comment]
@conklinbd @lfunkhouser 

Quick update: this issue has been resolved from previous merge. string.js, manifest.json and settings UI/js files were updated and now doesn't throw any exceptions as previously experienced. Closing out this issue.
