### ISSUE TITLE
Create GitHub Pages

### ISSUE THREAD

**Issue by kgonzago** [Esri/military-tools-webappbuilder#36]
create github pages to showcase the coordinate conversion and distance and direction widgets.

**Comment by nfeuerstein** [comment]
Coordinate Conversion Widget for 2.0 is listed on the Coordinate Conversion page: http://solutions.arcgis.com/defense/templates/coordinate-conversion/

Distance and Direction Widget is not mentioned or listed on the Solutions Pages: http://solutions.arcgis.com/defense/templates/distance-direction/ however, there is a download for it at 2.0: http://appsforms.esri.com/products/download/index.cfm?fuseaction=download.all#ArcGIS_for_Defense

**Comment by Dbarnes1** [comment]
@nfeuerstein with the December release this issue will be resolved, there is documentation waiting in solutions dev for Distance and Direction and Coordinate Conversion: http://solutionsdev.arcgis.com/defense/help/distance-direction/workflows/ellipse-awab/

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/solutions-webappbuilder-widgets#735
