### ISSUE TITLE
Allow the Ability to Input Coordinate and Then Input Distance Calculator Parameters to Draw Circle

### ISSUE THREAD

**Issue by mcalamito** [Esri/military-tools-webappbuilder#4]
I currently have to enter in Distance Calculator parameters, paste in coordinates/click on the Center Point Coordinate icon, and click on the map in order to get a Circle to draw.

**Comment by nfeuerstein** [comment]
Hitting Enter on your keyboard creates the circle.  This should be documented.

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/solutions-webappbuilder-widgets#738
