### ISSUE TITLE
distance-and-direction-widget - not creating line from 2 points when entered manually.

### ISSUE THREAD

**Issue by pshowalter** [Esri/military-tools-webappbuilder#42]
On lines tab, entered  Start Point, and End Point using DD format;  hit enter.  Line  is not created.
![image](https://cloud.githubusercontent.com/assets/6842145/15115063/16ed3ab2-15cb-11e6-8ea0-5489244a3744.png)

**Comment by MarkTorrey** [comment]
Currently not implemented, manual lines are to be addressed in another sprint
