### ISSUE TITLE
distance-and-direction-widget - Circles - Interactive

### ISSUE THREAD

**Issue by pshowalter** [Esri/military-tools-webappbuilder#48]
If user changes units to miles, then clicks to create circle, the circle created is enormous.

![image](https://cloud.githubusercontent.com/assets/6842145/15259811/64f5ce78-1921-11e6-81f5-271c85618aa2.png)

**Comment by MarkTorrey** [comment]
Hi Patrick, Committed an update to address this. Can you verify/check this again the build goes through.
