### ISSUE TITLE
Rate of travel needs to reflect the changes to the other add-ins

### ISSUE THREAD

**Issue by topowright** [Esri/military-tools-webappbuilder#8]
The rate of travel for the drop down on the Distance Calculator should look and calculate like this: 
1. Miles per/sec
2. Miles per/hour
3. Meters per/sec
4. Meters per/hour
5. Kilometers per/sec
6. Kilometers per/hour
7. Feet per/sec
8. Feet per/hour

**Comment by lfunkhouser** [comment]
This issue was moved to Esri/solutions-webappbuilder-widgets#736
